filetype off

" Vundle plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'flazz/vim-colorschemes'
Plugin 'severin-lemaignan/vim-minimap'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'xuhdev/vim-latex-live-preview'
Plugin 'vim-latex/vim-latex'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'Yggdroot/indentLine'
Plugin 'ajh17/VimCompletesMe'
Plugin 'othree/html5.vim'
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/syntastic'
Plugin 'joequery/Stupid-EasyMotion'
Plugin 'mattn/emmet-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomtom/tcomment_vim'
Plugin 'kien/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax enable
set ruler
set relativenumber
set number
set showmatch
set nowrap
set foldlevel=99
set hlsearch
set encoding=utf8
set backspace=indent,eol,start
set ignorecase

" tabs and indentation
" set noexpandtab
" set copyindent
" set preserveindent
" set softtabstop=0
" set shiftwidth=4
" set tabstop=4
" set smartindent
" set autoindent

" override plugins with these indenting options
autocmd FileType * set ts=4 sw=4 sts=0 smartindent noexpandtab

" override plugins to disable automatic commenting
autocmd FileType * set formatoptions-=cro


" show invisibles
set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

" show and move to open buffers
nnoremap <leader>b :ls<CR>:b<Space>

" theme settings. solarized, gruvbox, hybrid, Tomorrow-Night
let g:solarized_termtrans=1
set background=dark
colorscheme Tomorrow-Night

" set the airline theme: zenburn, base16, distinguished
let g:airline_theme='base16'

" vim-latex settings
set grepprg=grep\ -nH\ $*
filetype indent on
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats='pdf, aux'
let g:Tex_ViewRule_ps = 'open -a Preview'
let g:Tex_ViewRule_pdf = 'open -a Preview'
let g:Tex_ExecuteUNIXViewerInForeground = 0
" https://stackoverflow.com/questions/12650528/viewing-pdfs-with-vim-latex-suite-start-preview-shell-returned-127

" Linux Envince
" let g:Text_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
" let g:Tex_ViewRule_dvi = 'evince'

" Standard Vim key bindings
inoremap jj <Esc>
" imap ee <C-y>,
map <F2> :NERDTreeToggle<CR>
map s <leader><leader>w
map <S-d> <c-d>
map <S-u> <c-u>
map <S-e> <c-e>
map <S-y> <c-y>

" Tmux key bindings
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
let g:tmux_navigator_no_mappings = 1
let g:tmux_navigator_save_on_switch = 1 " autosave on leave
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-\> :TmuxNavigatePrevious<cr>

let g:ctrlp_dont_split = 'NERD'





